version: '3.8'

services:
  hadolint:
    image: hadolint/hadolint:v2.12.0
    working_dir: /mnt
    volumes:
      - ./:/mnt
    entrypoint: hadolint
    tty: true

  shellcheck:
    image: koalaman/shellcheck:v0.8.0
    volumes:
      - ./:/mnt

  kaniko:
    build: .
    environment:
      CI_REGISTRY: srv
      CI_REGISTRY_USER: usr
      CI_REGISTRY_PASSWORD: pwd
