#!/busybox/env sh
set -eu

mkdir -p /kaniko/.docker

srv="${CI_REGISTRY}"
upw="$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')"

echo "{\"auths\":{\"${srv}\":{\"auth\":\"${upw}\"}}}" > /kaniko/.docker/config.json
