name: Push to main

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Hadolint
        run: docker compose run --rm hadolint Dockerfile
      - name: Shellcheck
        run: docker compose run --rm shellcheck tools/*

  build-push:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Login to Docker
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v4.2.1
        with:
          push: true
          tags: technowledgy/kaniko-gitlab:latest

  dockerhub:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}